In [1]:
import numpy as np

In [5]:
arr= np.array([
    
        [1,2,3],
        [4,5,6],
        [7,8,9,]
])

In [6]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(arr[0])#zero based indexing

[1 2 3]


In [8]:
print(arr[1])

[4 5 6]


In [9]:
print(arr[-1])

[7 8 9]


In [10]:
print(arr[-3])

[1 2 3]


In [11]:
print(arr[1:3])#start is a inclusive,end exclusive

[[4 5 6]
 [7 8 9]]


In [12]:
print(arr[0:3:1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
print(arr[-1])

[7 8 9]


In [14]:
print(arr[:-1])

[[1 2 3]
 [4 5 6]]


In [15]:
print(arr[:-2])

[[1 2 3]]


In [16]:
print(arr [::-1])

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [20]:
print(arr)
print(arr[:,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6 9]


In [21]:
print(arr)
print(arr[:,0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]


In [22]:
print(arr[1:3:1,1:3:1])

[[5 6]
 [8 9]]


In [25]:
print(arr[0:2:1,0:2:1])

[[1 2]
 [4 5]]


In [35]:
print(arr[1:3:1,0:2:1])

[[4 5]
 [7 8]]


In [36]:
arr= np.array([
    
        [1,2,3],
        [4,5,6],
        [7,8,9,],
        [11,12,13]
])

In [37]:
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]]


In [ ]:
print(arr[1: