In [1]:
import numpy as np

In [2]:
arr=np.array([25,24,5,2])

In [3]:
print(arr+1)

[26 25  6  3]


In [5]:
brr=np.sqrt(arr)

In [6]:
print(np.round(brr))

[5. 5. 2. 1.]


In [7]:
print(np.floor(brr))

[5. 4. 2. 1.]


In [9]:
print(np.ceil(brr))

[5. 5. 3. 2.]


In [10]:
print(arr+brr)

[30.         28.89897949  7.23606798  3.41421356]


In [11]:
age = np.array([25,24,53,50,18,6,17])

In [12]:
print(age < 18)

[False False False False False  True  True]


In [13]:
print(age == 18)

[False False False False  True False False]


In [14]:
print(age >= 18)

[ True  True  True  True  True False False]


In [15]:
age[age<18] = 18
print(age)

[25 24 53 50 18 18 18]


In [17]:
age[age>50] = 50
print(age)

[25 24 50 50 18 18 18]
