In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
np.save("data.npy",arr)

In [3]:
read = np.load("data.npy")
print(read)

[1 2 3 4 5]


In [4]:
brr = np.array([6,7,8,9])
np.savez("data.npz",arr,brr)

In [5]:
read = np.load ("data.npz")

In [9]:
print(read)

NpzFile 'data.npz' with keys: arr_0, arr_1


In [10]:
print(read["arr_0"])

[1 2 3 4 5]


In [13]:
print(read["arr_1"])

[6 7 8 9]


In [14]:
#liner algebra

In [15]:
a=np.array([
    [2,4],
    [3,4]
])
b=np.array([
    [3,2],
    [4,2]
])

In [16]:
print(np.matmul(a,b))

[[22 12]
 [25 14]]
