In [1]:
import numpy as np

In [2]:
marks = np.array([50,100,65,85,76])

In [3]:
print(marks)

[ 50 100  65  85  76]


In [4]:
print(marks[marks>50])
print(marks)

[100  65  85  76]
[ 50 100  65  85  76]


In [5]:
pass_marks=(marks[marks<50])

In [6]:
print(marks)

[ 50 100  65  85  76]


In [10]:
arr=np.array([
    [1,2,3],
    [4,5,6]
])

In [11]:
even = arr[arr%2==0]
print(even)

[2 4 6]


In [12]:
even = arr[(arr%2==0) |(arr == 1)]
print(even)

[1 2 4 6]


In [14]:
even = np.where(arr%2==0, arr,5)
print(even)

[[5 2 5]
 [4 5 6]]
