In [1]:
import numpy as  np

In [2]:
array = np.array([1,2,3,4,5])

In [3]:
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
print(array)
print(array.dtype)

[1 2 3 4 5]
int8


In [5]:
array = np.array([1,2,3,4,5],dtype=np.int8)

In [7]:
# int8,int16,int32,int64
# 2^8 =256 => -128 -> 0 -> 127

In [9]:
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")

[1 2 3 4 5]
int8
5 bytes


In [10]:
array = np.array([200,400,145,123,700],dtype=np.int16)

In [11]:
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")


[200 400 145 123 700]
int16
10 bytes


In [12]:
array = np.array([1.2,3.4,5.6,7.8,9.])

In [13]:
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")



[1.2 3.4 5.6 7.8 9. ]
float64
40 bytes


In [14]:
array = np.array([1.2,3.4,5.6,7.8,9.],dtype = np.float16)

In [15]:
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")



[1.2 3.4 5.6 7.8 9. ]
float16
10 bytes


In [16]:
array = np.array([200,400,145,123,700],dtype=np.float16)


In [17]:
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")


[200. 400. 145. 123. 700.]
float16
10 bytes


In [18]:
array = np.array([200,400,145,123,700],dtype=np.str_)


In [19]:
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")

['200' '400' '145' '123' '700']
<U3
60 bytes


In [20]:
array = np.array([200,4001,145,123,700],dtype=np.str_)


In [21]:
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes"}

SyntaxError: closing parenthesis '}' does not match opening parenthesis '(' (4066578169.py, line 3)

In [22]:
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")

['200' '4001' '145' '123' '700']
<U4
80 bytes


In [23]:
array = np.array(["this","is","kani"])

In [24]:
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")


['this' 'is' 'kani']
<U4
48 bytes


In [25]:
array = np.array([true,false,true,flase])

NameError: name 'true' is not defined

In [26]:
array = np.array ([True,Flase,True,Flase])

NameError: name 'Flase' is not defined

In [27]:
array = np.array ([True,False,True,False])

In [28]:
print(array)
print(array.dtype)
print(f"{array.npbytes} bytes")

[ True False  True False]
bool


AttributeError: 'numpy.ndarray' object has no attribute 'npbytes'

In [29]:
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")

[ True False  True False]
bool
4 bytes


In [30]:
array = np.array(["this","is","kani"],dtype=",u3")

SyntaxError: invalid syntax (<unknown>, line 1)

In [31]:
array = np.array(["this","is","kani"],dtype=",U3")

SyntaxError: invalid syntax (<unknown>, line 1)

In [32]:
array = np.array(["this","is","kani"],dtype="<U3")

In [36]:
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")


['1' '2' 'True' 'kani']
<U21
336 bytes


In [34]:
array = np.array([1,2,True,"kani"])

In [35]:
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")


['1' '2' 'True' 'kani']
<U21
336 bytes


In [37]:
array = np.array([1,2,True,"kani"],dtype=np.object_)

In [41]:
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")


[1 2 3 4 5]
int64
40 bytes


In [39]:
array=np.array([1,2,3,4,5])

In [40]:
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")


[1 2 3 4 5]
int64
40 bytes


In [42]:
array=arrya.astype(np.str_)

NameError: name 'arrya' is not defined

In [43]:
array=array.astype(np.str_)

In [44]:
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")


['1' '2' '3' '4' '5']
<U21
420 bytes
