In [1]:
import numpy as np

In [2]:
arr = np.array([
        [1,2,3],
        [4,5,6],
        [7,8,9]
])

In [3]:
brr = np.array([1,2,3])

In [4]:
print(arr.shape)
print(brr.shape)
print(arr*brr)

(3, 3)
(3,)
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


In [5]:
arr=np.zeros(10)

In [6]:
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
arr = np.zeros((10,2))

In [9]:
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [12]:
arr = np.zeros((1,10,2))

In [13]:
print(arr)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [14]:
arr = np.full((2,3),45)

In [15]:
print(arr)

[[45 45 45]
 [45 45 45]]


In [16]:
arr = np.full((3,2,3),45)

In [17]:
print(arr)

[[[45 45 45]
  [45 45 45]]

 [[45 45 45]
  [45 45 45]]

 [[45 45 45]
  [45 45 45]]]


In [20]:
arr = np.eye(5)

In [22]:
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [27]:
arr=np.empty([3,2,4])
print(arr)

[[[6.23042070e-307 1.86918699e-306 1.69121096e-306 1.33511018e-306]
  [2.31422756e-306 7.56587585e-307 1.37961302e-306 1.05699242e-307]]

 [[8.01097889e-307 1.78020169e-306 7.56601165e-307 1.02359984e-306]
  [1.42417221e-306 7.56593017e-307 1.37961709e-306 1.60218491e-306]]

 [[1.69121096e-306 1.60220800e-306 1.42417629e-306 9.34609111e-307]
  [1.60221479e-306 9.34607074e-307 2.22522596e-306 2.22522596e-306]]]


In [32]:
arr = np.arange(0,101,15)#start,end,step
print(arr)

[ 0 15 30 45 60 75 90]


In [36]:
arr = np.linspace(0,100,5)
print(arr)

[  0.  25.  50.  75. 100.]


In [37]:
print(np.min(arr))

0.0


In [38]:
print(np.var(arr))

1250.0


In [39]:
print(np.argmin(arr))

0


In [40]:
print(np.argmax(arr))

4
